name: app-task
services:
  postgres:
    image: postgres:16
    container_name: app-task-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432'
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    networks:
      - postgres
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: app-task-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '8083:80'
    networks:
      - postgres
    restart: always
    volumes:
      - ./db/pgadmin_data:/var/lib/pgadmin
volumes:
  db:
networks:
  postgres:
